### ISSUE TITLE
Futures Module

### ISSUE THREAD

**Issue by eightysixed** [paulbarbu/IRC-Bot#36]
Hello! :) What exactly am I doing wrong where I keep getting "ImportError: No module named futures" when trying to execute the script? I've pip'd the module in, and am still seeing this? I'm sure it's something ridiculously easy. Any advice? Thanks!

**Comment by sudosoldier** [comment]
I am having the same issue as OP,

python --version
Python 2.7.6

pip freeze
futures==3.0.2

**Comment by adriweb** [comment]
Same here, solved by doing :

`import concurrent.futures` instead of `import features`
and 
`with concurrent.futures.ProcessPoolExecutor` instead of `with futures.ProcessPoolExecutor`

**Comment by ohdb** [comment]
*For Future Help*
you can leave this how it is you dont need to edit the file just install the module

run this code and it should run perfectly
`wget https://bootstrap.pypa.io/get-pip.py; python get-pip.py;pip install futures`
